<?php

namespace CoreBundle\Repository;

/**
 * articleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastFiveElements()
    {
        return $this->createQueryBuilder('a')   // alias
                    ->setMaxResults(5)          // 5 articles
                    ->addOrderBy('a.dateParution', 'DESC')  // tri par date parution dernier créé avant
                    ->getQuery()
                    ->getResult();

    }
}
